import { useMemo } from 'react';
import { motion } from 'framer-motion';
import { useReduceMotion } from '@/lib/reduce-motion';
import { bruteForce, humanizeSeconds } from '@/lib/crypto-lab/bruteforce';

/**
 * Brute-force curve comparison.
 *
 * Shows three preset password configurations side by side and renders a
 * log-scale exponential growth curve so the user sees, intuitively, how
 * each added character or character-set widening multiplies the search
 * space. The fast-hash attacker rate is used as the standard baseline
 * so the times are directly comparable.
 */

const ATTACKER_RATE = 1e10; // 10 billion guesses/sec — modern GPU rig

interface Preset {
  id: string;
  label: string;
  charset: number;
  length: number;
  accent: string;
  caption: string;
}

const PRESETS: Preset[] = [
  {
    id: 'weak',
    label: '8 lowercase',
    charset: 26,
    length: 8,
    accent: '#f04438',
    caption: 'a common "short word" password',
  },
  {
    id: 'mid',
    label: '12 mixed',
    charset: 62,
    length: 12,
    accent: '#f79009',
    caption: 'letters, digits, mixed case',
  },
  {
    id: 'strong',
    label: '16 random',
    charset: 95,
    length: 16,
    accent: '#27a644',
    caption: 'generated by a password manager',
  },
];

const MAX_LEN = 18;

export function BruteForceCurve() {
  const reduceMotion = useReduceMotion();
  /** Per-preset summary metrics. */
  const summaries = useMemo(
    () =>
      PRESETS.map((p) => ({
        ...p,
        result: bruteForce({
          charsetSize: p.charset,
          length: p.length,
          rate: ATTACKER_RATE,
        }),
      })),
    [],
  );

  /** Pre-build the curve series for each preset (length → log10 keyspace). */
  const series = useMemo(() => {
    return PRESETS.map((p) => {
      const points: { length: number; log10: number }[] = [];
      for (let L = 1; L <= MAX_LEN; L++) {
        points.push({ length: L, log10: L * Math.log10(p.charset) });
      }
      return { id: p.id, accent: p.accent, points };
    });
  }, []);

  /** Shared y-axis max across all presets so the curves stay comparable. */
  const maxLog = useMemo(() => {
    let m = 0;
    for (const s of series) for (const pt of s.points) if (pt.log10 > m) m = pt.log10;
    return m;
  }, [series]);

  return (
    <div className="space-y-5">
      {/* Curve chart */}
      <div className="rounded-xl border border-hairline bg-surface-2/40 p-4">
        <div className="flex items-baseline justify-between">
          <div className="text-micro font-medium uppercase tracking-[0.18em] text-ink-tertiary">
            Search space · log₁₀ scale
          </div>
          <div className="font-mono text-micro tabular-nums text-ink-tertiary">
            attacker: 10¹⁰ guesses/sec
          </div>
        </div>

        <div className="relative mt-3 h-56">
          <ChartGrid maxLog={maxLog} />
          <svg
            viewBox={`0 0 ${MAX_LEN - 1} 100`}
            preserveAspectRatio="none"
            className="absolute inset-0 h-full w-full overflow-visible"
          >
            {series.map((s, i) => {
              const d = s.points
                .map((pt, idx) => {
                  const x = idx;
                  const y = 100 - (pt.log10 / maxLog) * 100;
                  return `${idx === 0 ? 'M' : 'L'} ${x} ${y}`;
                })
                .join(' ');
              return (
                <motion.path
                  key={s.id}
                  d={d}
                  fill="none"
                  stroke={s.accent}
                  strokeWidth={0.5}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  vectorEffect="non-scaling-stroke"
                  initial={{ pathLength: reduceMotion ? 1 : 0, opacity: 0 }}
                  whileInView={{ pathLength: 1, opacity: 1 }}
                  viewport={{ once: true }}
                  transition={
                    reduceMotion
                      ? { duration: 0 }
                      : { duration: 1.1, delay: 0.15 + i * 0.15, ease: [0.16, 1, 0.3, 1] }
                  }
                  style={{ filter: `drop-shadow(0 0 6px ${s.accent}55)` }}
                />
              );
            })}
          </svg>

          {/* x-axis label */}
          <div className="absolute -bottom-5 left-0 right-0 flex justify-between font-mono text-micro text-ink-tertiary">
            <span>1</span>
            <span>length →</span>
            <span>{MAX_LEN}</span>
          </div>
        </div>
      </div>

      {/* Preset summary cards */}
      <div className="grid gap-3 sm:grid-cols-3">
        {summaries.map((s) => (
          <motion.div
            key={s.id}
            initial={{ opacity: 0, y: 8 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            className="rounded-xl border border-hairline bg-surface-1/60 p-4"
          >
            <div className="flex items-baseline justify-between">
              <div className="text-[13px] font-medium text-ink">{s.label}</div>
              <span
                className="font-mono text-micro tabular-nums"
                style={{ color: s.accent }}
              >
                {s.charset}^{s.length}
              </span>
            </div>
            <p className="mt-0.5 text-[11px] text-ink-tertiary">{s.caption}</p>

            <div className="mt-3 space-y-1.5">
              <Row label="Order" value={`≈10^${Math.round(s.result.log10)}`} />
              <Row label="Avg. crack" value={humanizeSeconds(s.result.secondsAvg)} accent={s.accent} />
            </div>
          </motion.div>
        ))}
      </div>

      <p className="text-[12px] leading-relaxed text-ink-tertiary">
        Doubling the alphabet only widens the base; adding one character
        multiplies the entire keyspace. Length is exponential — which is
        why a long passphrase beats a short complex string every time.
      </p>
    </div>
  );
}

function ChartGrid({ maxLog }: { maxLog: number }) {
  // Render 4 horizontal log-decade gridlines.
  const lines = 4;
  return (
    <div className="absolute inset-0 flex flex-col justify-between">
      {Array.from({ length: lines + 1 }).map((_, i) => {
        const frac = i / lines;
        const labelLog = Math.round(maxLog * (1 - frac));
        return (
          <div key={i} className="relative">
            <div className="absolute inset-x-0 h-px bg-hairline/60" />
            <span className="absolute -top-2 left-0 font-mono text-micro text-ink-tertiary">
              10^{labelLog}
            </span>
          </div>
        );
      })}
    </div>
  );
}

function Row({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div className="flex items-baseline justify-between text-[11px]">
      <span className="text-ink-subtle">{label}</span>
      <span
        className="font-mono tabular-nums"
        style={{ color: accent ?? '#d0d6e0' }}
      >
        {value}
      </span>
    </div>
  );
}
